---
title: "Why to contribute"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

1. Every data contributor automatically becomes **co-author of pmird** and therefore can get credit for his/her effort in collecting the data.

2. Every data contributor who submits data prior January 31, 2021 becomes **co-author of our data paper** that describes pmird.

4. Every data contributor also becomes **co-author of another data compendium [dpeatland]()** because I plan to integrate the data from pmird into dpeatland.

5. **Full transparency**: See [what I plan to do with the data](a02-What-I-plan-to-do-with-the-data.html).

6. Every contribution makes pmird **more useful for research**, including your own! At the end of my PhD project, pmird will be published such that it can be the basis for future research.

7. I want that **every data contributor is appropriately acknowledged** for his/her effort. For this reason, there is a special citing policy that does not only require to cite pmird, but also your original data set, meaning that your contribution does not perish silently within pmird.

Find out how to contribute [here!](a03-How-to-contribute.html)
