---
title: "Data dictionary"
toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r packages}
library(magrittr)
library(kableExtra)
```


This article is the *data dictionary* for the template files of pmird. The data dictionary contains a description of all fields of the data tables where data contributors can enter their data. In the following, there is a section for each file in [___ todo: fill in]().

## general_info

```{r general-info}
rbind( c("data_title", "A string with the title of the data set.", "Mid infrared spectra and physicochemical data of two peat cores from Alaskian bogs."),
       c("data_version", "A string with the version of the data set.", "1.2"),
       c("data_year_of_creation", "A numeric value with the year of creation of the data set.", "2012"),
       c("data_license", "A string with the license of the data set. This must be CC-BY 4.0 for the data to be usable in pmird.", "CC-BY 4.0"),
       c("data_url", "The online address where the data has been published or is available (fill in if available).", "doerepo.org/data/df345.345.1233"),
       c("data_doi", "A string with the digital object identifier (DOI) of the data set (fill in if available).", "df345.345.1233"),
       c("data_citing_statement", "A string with a verbal statement of how to cite the data set. This will be used to automatically generate citations of the data set in pmird.", "John Doe (2012): Mid infrared spectra and physicochemical data of two peat cores from Alaskian bogs. URL: doerepo.org/data/df345.345.1233. DOI: df345.345.1233."),
       c("data_abstract", "A string with a verbal description summarising the data set.", "..."),
       c("data_keywords", 'A string with keywords for the data set. Different keywords have to be separated with ";". ___ todo: search if there is a common dictionary for terms to use.', "peat; FTIR; Alaska; bog; radiocarbon dating; nitrogen; carbon; oxygen; bulk density;")) %>%
  as.data.frame() %>%
  kableExtra::kable(col.names = c("field", "description", "example")) %>%
  kableExtra::column_spec(2, width = "25em") %>%
  kableExtra::column_spec(3, width = "7em")
```

## authors

```{r authors}
rbind(c("author_id", "A numeric id for the author (starting with 1 and increasing by 1).", "1"),
      c("author_surname", "A string with the surname of the author.", "Doe"),
      c("author_given_name", "A string with the given name of the author.", "John"),
      c("author_email_address", "A string with the email address of the author.", "john.doe@foo.com"),
      c("author_orcid", "A string with the ORCID id of the author (if available).", "0000-0002-3993-1182"),
      c("author_affiliation", "A string with the affiliation of the author.", "Institute for peat research, John Doe University, Main street 32, GB-34787")) %>%
  as.data.frame() %>%
  kableExtra::kable(col.names = c("field", "description", "example")) %>%
  kableExtra::column_spec(2, width = "25em") %>%
  kableExtra::column_spec(3, width = "15em")
```

## site_info

```{r site-info}
rbind(c("site_id", "A numeric id for the site (starting with 1 and increasing by 1).", "1"),
      c("site-name", "A string with the site name.", "Great Doe Bog"),
      c("site_longitude", "A string with the longitude coordinates of the site (based on the WGS 84 reference system) [°W].", "79.982"),
      c("site_latitude", "A string with the latitude coordinates of the site (based on the WGS 84 reference system) [°N].", "40.446"),
      c("site_altitude", "A numeric value representing the altitude [m above sea level] of the site", "533")
      ) %>%
  as.data.frame() %>%
  kableExtra::kable(col.names = c("field", "description", "example"), escape = FALSE) %>%
  kableExtra::column_spec(2, width = "25em") %>%
  kableExtra::column_spec(3, width = "15em")
```

## sample_data

```{r sample-data}
rbind(c("sample_id", "A numeric id for the sample (starting with 1 and increasing by 1).", "1"),
      c("core_label", "A string representing a label for the peat core (if the sample was taken from a peat core). This can be a custom label.", "FT_II"),
      c("sampling_date", "A string with the date when the sample was collected (in the field) with the format YYYY-MM-DD.", "2010-05-15"),
      c("sampling_longitude", "A numeric value representing the longitude coordinates of the exact sampling position (based on the WGS 84 reference system) [°W].", "79.983"),
      c("sampling_longitude_err", "A numeric value representing the measurement error of the longitude coordinates of the exact sampling position (based on the WGS 84 reference system) [°W].", "0.003"),
      c("sampling_latitude", "A numeric value representing the latitude coordinates of the exact sampling position (based on the WGS 84 reference system) [°N].", "40.447"),
      c("sampling_latitude_err", "A numeric value representing the measurement error of the latitude coordinates of the exact sampling position (based on the WGS 84 reference system) [°N].", "0.005"),
      c("sampling_altitude", "A numeric value representing the altitude of the exact sampling position [m above sea level].", "543"),
      c("sampling_altitude_err", "A numeric value representing the measurement error of the altitude of the exact sampling position [m above sea level].", "5.2"),
      c("site_id", "A numeric id for the site where the sample was collected. This should be the corresponding value in the file site_info.csv.", "1"),
      c("sample_depth_lower", "A numeric value representing the depth of the lower boundary of a sample relative to the land surface (e.g. peat surface).", "15 cm"),
      c("sample_depth_lower_err", "", "0.2 cm"),
      c("sample_depth_upper", "A numeric value representing the depth of the upper boundary of a sample relative to the land surface (e.g. peat surface).", "12 cm"),
      c("sample_depth_upper_err", "", "0.2 cm"),
      c("sample_type", "A string describing the type of the sample. Must be one of 'peat', 'dom', 'vegetation', 'litter'. You can invent a new category if these are not matching.", "peat"),
      c("sample_microhabitat", "A string describing the microhabitat where the sample was collected. For peat, this should be one of 'hummock', 'hollow', 'lawn', 'pond'. In other cases, a custom value can be used.", "hummock"),
      c("sample_treatment", "A string with an description of an experimental tratment if this was applied. By default, this should be 'control', indicating that there was no manipulation. If there was any experimental manipulation, this can be abbreviated by a label (e.g. by a treatment level) that is defined in the textual description of the project (in the file 'description.docx').", "control"),
      c("comments", "A free text field where you can enter all information related to the sample that is not covered by the remaining fields. For example you could provide information on potential contamination sources, issues with specific parameters, additional information to the sampling site, e.g. present vegetation, past vegetation, specific conditions during sampling, ... .", "..."),
      c("N", "A numeric value representing the nitrogen mass content of the sample [mass-%].", "1.345"),
      c("N_err", "A numeric value representing the measurement error of the nitrogen mass content value of the sample [mass-%].", "0.02"),
      c("C", "A numeric value representing the carbon mass content of the sample [mass-%].", "35.44"),
      c("C_err", "A numeric value representing the measurement error of the carbon mass content value of the sample [mass-%].", "0.3"),
      c("O", "A numeric value representing the oxygen mass content of the sample [mass-%].", "28.54"),
      c("O_err", "A numeric value representing the measurement error of the oxygen mass content value of the sample [mass-%].", "1.2"),
      c("H", "A numeric value representing the hydrogen mass content of the sample [mass-%].", "5.16"),
      c("H_err", "A numeric value representing the measurement error of the hydrogen mass content value of the sample [mass-%].", "0.3"),
      c("S", "A numeric value representing the sulfur mass content of the sample [mass-ppm].", "472.0"),
      c("S_err", "A numeric value representing the measurement error of the sulfur mass content value of the sample [mass-ppm].", "12.4"),
      c("P", "A numeric value representing the phosphorous mass content of the sample [mass-ppm].", "263.6"),
      c("P_err", "A numeric value representing the measurement error of the phosphorous mass content value of the sample [mass-ppm].", "5.4"),
      c("K", "A numeric value representing the potassium mass content of the sample [mass-ppm].", "481.0"),
      c("K_err", "A numeric value representing the measurement error of the potassium mass content value of the sample [mass-ppm].", "5.6"),
      c("Ca", "A numeric value representing the calcium mass content of the sample [mass-ppm].", "1353.0"),
      c("Ca_err", "A numeric value representing the measurement error of the calcium mass content value of the sample [mass-ppm].", "7.6"),
      c("Na", "A numeric value representing the sodium mass content of the sample [mass-ppm].", "104.0"),
      c("Na_err", "A numeric value representing the measurement error of the sodium mass content value of the sample [mass-ppm].", "6.7"),
      c("Mg", "A numeric value representing the magnesium mass content of the sample [mass-ppm].", "520.0"),
      c("Mg_err", "A numeric value representing the measurement error of the magnesium mass content value of the sample [mass-ppm].", "3.2"),
      c("Al", "A numeric value representing the aluminium mass content of the sample [mass-ppm].", "859.0"),
      c("Al_err", "A numeric value representing the measurement error of the aluminium mass content value of the sample [mass-ppm].", "3.2"),
      c("Si", "A numeric value representing the silicium mass content of the sample [mass-ppm].", "1681.5"),
      c("Si_err", "A numeric value representing the measurement error of the silicium mass content value of the sample [mass-ppm].", "9.7"),
      c("Cl", "A numeric value representing the chlorine mass content of the sample [mass-ppm].", "410.0"),
      c("Cl_err", "A numeric value representing the measurement error of the chlorine mass content value of the sample [mass-ppm].", "5.4"),
      c("Ti", "A numeric value representing the titanium mass content of the sample [mass-ppm].", "523.6"),
      c("Ti_err", "A numeric value representing the measurement error of the titanium mass content value of the sample [mass-ppm].", "5.6"),
      c("Cr", "A numeric value representing the chromium mass content of the sample [mass-ppm].", "4.02"),
      c("Cr_err", "A numeric value representing the measurement error of the chromium mass content value of the sample [mass-ppm].", "0.04"),
      c("Mn", "A numeric value representing the manganese mass content of the sample [mass-ppm].", "23.6"),
      c("Mn_err", "A numeric value representing the measurement error of the manganese mass content value of the sample [mass-ppm].", "0.04"),
      c("Fe", "A numeric value representing the iron mass content of the sample [mass-ppm].", "468"),
      c("Fe_err", "A numeric value representing the measurement error of the iron mass content value of the sample [mass-ppm].", "2.3"),
      c("Cu", "A numeric value representing the copper mass content of the sample [mass-ppm].", "10.8"),
      c("Cu_err", "A numeric value representing the measurement error of the copper mass content value of the sample [mass-ppm].", "0.2"),
      c("Zn", "A numeric value representing the zinc mass content of the sample [mass-ppm].", "3.9"),
      c("Zn_err", "A numeric value representing the measurement error of the zinc mass content value of the sample [mass-ppm].", "0.3"),
      c("As", "A numeric value representing the arsenic mass content of the sample [mass-ppm].", "1.19"),
      c("As_err", "A numeric value representing the measurement error of the arsenic mass content value of the sample [mass-ppm].", "0.3"),
      c("Br", "A numeric value representing the bromine mass content of the sample [mass-ppm].", "26.55"),
      c("Br_err", "A numeric value representing the measurement error of the bromine mass content value of the sample [mass-ppm].", "0.5"),
      c("Rb", "A numeric value representing the rubidium mass content of the sample [mass-ppm].", "1.8"),
      c("Rb_err", "A numeric value representing the measurement error of the rubidium mass content value of the sample [mass-ppm].", "0.1"),
      c("Sr", "A numeric value representing the strontium mass content of the sample [mass-ppm].", "8.8"),
      c("Sr_err", "A numeric value representing the measurement error of the strontium mass content value of the sample [mass-ppm].", "0.2"),
      c("Ba", "A numeric value representing the barium mass content of the sample [mass-ppm].", "482.7"),
      c("Ba_err", "A numeric value representing the measurement error of the barium mass content value of the sample [mass-ppm].", "2"),
      c("Pb", "A numeric value representing the lead mass content of the sample [mass-ppm].", "29.72"),
      c("Pb_err", "A numeric value representing the measurement error of the lead mass content value of the sample [mass-ppm].", "0.4"),
      c("mass", "A numeric value representing the mass of the sample [g]. This is the mass of the extracted sample and masses of subsets of the sample may differ (for example: A peat layer dried at 105 degree C may have a mass of 200 g. This is the value to be reported. After milling, 10 g may be used to measure the pH value (this value should not be reported here, but in the description of the methods or in column 'comments'.))", "200"),
      c("mass_err", "A numeric value representing the measurement error of the mass of the sample [g].", "0.01"),
      c("volume", "A numeric value representing the volume of the sample [cm<sup>3</sup>].", "20"),
      c("volume_err", "A numeric value representing the measurement error of the volume of the sample [cm<sup>3</sup>].", "0.1 cm<sup>3</sup>"),
      c("bulk_density", "A numeric value representing the bulk density of the sample [g cm<sup>-3</sup>].", "0.2"),
      c("bulk_density_err", "A numeric value representing the measurement error of the bulk density of the sample [g cm<sup>-3</sup>].", "0.03"),
      c("loss_on_ignition", "A numeric value representing the loss on ignition of the sample [mass-%].", "87.5"),
      c("loss_on_ignition_err", "A numeric value representing the measurement error of the loss on ignition value of the sample [mass-%].", "4.3"),
      c("pH", "A numeric value representing the pH value of the sample.", "5.4"),
      c("pH_err", "A numeric value representing the measurement error of the pH value value of the sample.", "0.8"),
      c("electron_accepting_capacity", "A numeric value representing the electron accepting capacity (EAC) of the sample [&mu;mol (g C)<sup>-1</sup>].", "115.81"),
      c("electron_accepting_capacity_err", "A numeric value representing the measurement error of the electron accepting capacity (EAC) of the sample [&mu;mol (g C)<sup>-1</sup>].", "75.63"),
      c("electron_donating_capacity", "A numeric value representing the electron donating capacity (EDC) of the sample [&mu;mol (g C)<sup>-1</sup>].", "376.34"),
      c("electron_donating_capacity_err", "A numeric value representing the measurement error of the electron donating capacity (EDC) of the sample [&mu;mol (g C)<sup>-1</sup>].", "56.45"),
      c("heat_of_combustion", "A numeric value representing the heat of combustion of the sample (using a molecular formular informed by element measurements of the sample) [kJ mol<sup>-1</sup>].", "-780"),
      c("heat_of_combustion_err", "A numeric value representing the measurement error of the heat of combustion of the sample (using a molecular formular informed by element measurements of the sample) [kJ mol<sup>-1</sup>].", "25"),
      c("enthalpy_of_formation", "A numeric value representing the standard enthalpy of formation of the sample (using a molecular formular informed by element measurements of the sample) [kJ mol<sup>-1</sup>].", "450"),
      c("enthalpy_of_formation_err", "A numeric value representing the measurement error of the standard enthalpy of formation of the sample (using a molecular formular informed by element measurements of the sample) [kJ mol<sup>-1</sup>].", "25"),
      c("entropy_of_formation", "A numeric value representing the standard entropy of formation of the sample [J K<sup>-1</sup> mol<sup>-1</sup>].", "450"),
      c("entropy_of_formation_err", "A numeric value representing the standard entropy of formation of the sample [J K<sup>-1</sup> mol<sup>-1</sup>].", "20"),
      c("Gibbs_energy_of_formation", "A numeric value representing the standard Gibbs energy of formation of the sample [kJ mol<sup>-1</sup>].", "450"),
      c("Gibbs_energy_of_formation_err", "A numeric value representing the measurement error of the standard Gibbs energy of formation of the sample [kJ mol<sup>-1</sup>].", "25"),
      c("Klason_lignin_content", "A numeric value representing the Klason lignin content of the sample [mass-%].", "26"),
      c("Klason_lignin_content_err", "A numeric value representing measurement error of the Klason lignin content of the sample [mass-%].", "1"),
      c("holocellulose_mass_content", "A numeric value representing the holocellulose content of the sample [mass-%].", "45"),
      c("holocellulose_mass_content_err", "A numeric value representing measurement error of the holocellulose content of the sample [mass-%].", "1.5"),
      c("age_14C", "A numeric value representing the mean value of the uncalibrated <sup>14</sup>C age of the sample [yr BP].", "1200"),
      c("age_14C_err", "A numeric value representing the error of the uncalibrated <sup>14</sup>C age of the sample [yr].", "80"),
      c("lab_code_14C", "A string representing a code for the laboratory where the <sup>14</sup>C activities were measured (<sup>14</sup>C ages were determined).", "MAMS-"),
      c("activity_210Pb", "A numeric value representing the measured mean value of the <sup>210</sup>Pb activity of the sample [Bq kg<sup>-1</sup>].", "370"),
      c("activity_210Pb_err", "A numeric value representing the measurement error of the <sup>210</sup>Pb activity of the sample [Bq kg<sup>-1</sup>].", "12.3"),
      c("mass_210Pb", "A numeric value representing the measured mass of the subsample on which the <sup>210</sup>Pb activity of the sample was measured [g].", "6"),
      c("mass_210Pb_err", "A numeric value representing the measurement error of the mass of the subsample on which the <sup>210</sup>Pb activity of the sample was measured [g].", "0.01"),
      c("volume_210Pb", "A numeric value representing the measured volume of the subsample on which the <sup>210</sup>Pb activity of the sample was measured [cm<sup>3</sup>].", "10"),
      c("volume_210Pb_err", "A numeric value representing the error of the volume of the subsample on which the <sup>210</sup>Pb activity of the sample was measured [cm<sup>3</sup>].", "0.1"),
      c("bulk_density_210Pb", "A numeric value representing the mass density of the subsample on which the <sup>210</sup>Pb activity of the sample was measured [g cm<sup>-3</sup>].", "0.2"),
      c("bulk_density_210Pb_err", "A numeric value representing the error of the mass density of the subsample on which the <sup>210</sup>Pb activity of the sample was measured [g cm<sup>-3</sup>].", "0.03"),
      c("counting_method_210_Pb", "A string representing a description of the counting method used for measuring the <sup>210</sup>Pb activities (one of alpha, beta or gamma).", "alpha"),
      c("laboratory_label_210Pb", "A string representing a label (preferentially a code, similarly to lab_code_14C) for the laboratory where the <sup>210</sup>Pb activities were measured.", "MAMS-"),
      c("background_activity_reached_210Pb", "A logical value (TRUE or FALSE) indicating if the corresponding  <sup>210</sup>Pb activity in the same row (activity_210Pb) represents (according to the interpretation of the person who dated the core) the supported (background) <sup>210</sup>Pb activity (TRUE) or not (FALSE).", "TRUE"),
      c("activity_137Cs", "A numeric value representing the measured mean value of the <sup>137</sup>Cs activity of the sample [DPM g<sup>-1</sup>] (DPM are disintegrations per second).", "9.1"),
      c("activity_137Cs_err", "A numeric value representing the measurement error of the <sup>137</sup>Cs activity of the sample [DPM g<sup>-1</sup>] (DPM are disintegrations per second).", "1.2"),
      c("year_137Cs", "A numeric value representing the age that was assigned to the sample based on the <sup>137</sup>Cs activity inventory [yr AD] (e.g. by relating it to the date of the Chernobyl accident).", "1963"),
      c("hydraulic_conductivity", "A numeric value representing the saturated hydraulic conductivity (K<sub>s</sub>) of the sample [cm h<sup>-1</sup>].", "4.7863"),
      c("hydraulic_conductivity_err", "A numeric value representing the error of the saturated hydraulic conductivity (K<sub>s</sub>) of the sample [cm h<sup>-1</sup>].", "0.02"),
      c("porosity", "A numeric value representing the porosity of the sample [volume-%].", "82.3"),
      c("porosity_err", "A numeric value representing the error of the porosity of the sample [volume-%].", "2.4"),
      c("macroporosity", "A numeric value representing the macroporosity of the sample [volume-%]. Since the term 'macroporosity' is ambiguous, the term should be defined in the description of the methods if values are available.", "56.3"),
      c("macroporosity_err", "A numeric value representing the error of the macroporosityporosity of the sample [volume-%].", "2.4")
      ) %>%
  as.data.frame() %>%
  kableExtra::kable(col.names = c("field", "description", "example"), escape = FALSE) %>%
  kableExtra::column_spec(2, width = "25em") %>%
  kableExtra::column_spec(3, width = "15em")
```

## sample_mir

```{r sample-mir}
rbind(
  c("wavenumber", "A numeric value representing the wavenumber value (x axis value) of the mid infrared spectra [cm<sup>-1</sup>].", "599.2")
      ) %>%
  as.data.frame() %>%
  kableExtra::kable(col.names = c("field", "description", "example"), escape = FALSE) %>%
  kableExtra::column_spec(2, width = "25em") %>%
  kableExtra::column_spec(3, width = "15em")
```

## sample_mir_error

```{r sample-mir-error}
rbind(
  c("wavenumber", "A numeric value representing the wavenumber value (x axis value) of the mid infrared spectra [cm<sup>-1</sup>].", "599.2")
      ) %>%
  as.data.frame() %>%
  kableExtra::kable(col.names = c("field", "description", "example"), escape = FALSE) %>%
  kableExtra::column_spec(2, width = "25em") %>%
  kableExtra::column_spec(3, width = "15em")
```
